### ISSUE TITLE
Update MosaicJSON stac_ipyleaflet Notebook

### ISSUE THREAD

**Issue by smk0033** [MAAP-Project/maap-documentation#364]
## Description
While adding the stac_ipyleaflet DOI to [visualize_mosaic_stac_ipyleaflet.ipynb](https://docs.maap-project.org/en/latest/technical_tutorials/visualization/visualize_mosaic_stac_ipyleaflet.html), I noticed some updates could be made to help follow [guidelines](https://nasa-impact.github.io/veda-docs/contributing/docs-and-notebooks.html).

This notebook should be reviewed using the guidelines and should include the following components:
1. Style
2. Rendering Information
3. Notebook Sections

## Tasks
- [x] Style should be consistent with guidance provided
- [x] Rendering information should be complete and accurate
- [x] Ensure notebooks include the recommended standard sections

**Comment by smk0033** [comment]
PR: https://github.com/MAAP-Project/maap-documentation/pull/366

**Comment by smk0033** [comment]
Approved and merged
